defaultMinusAccount: Assets:FIXME
defaultPlusAccount: Expenses:FIXME
defaultCashAccount: Assets:Zuo:Savings:ICBC:2042
defaultCurrency: CNY
title: 测试
icbc:
  rules:
    - txType: 他行汇入
      peerAccountNum: "6214****0225"
      targetAccount: Assets:Zuo:Savings:CMB:0225

    - txType: 跨行汇款
      peerAccountNum: "6214****0225"
      targetAccount: Assets:Zuo:Savings:CMB:0225

    - peerAccountNum: "1001****2505"
      txType: 缴费
      targetAccount: Expenses:Education:Tuition

    - peerAccountNum: "1001****2127"
      targetAccount: Expenses:Education:Tuition

    - peerAccountNum: "1001****5185"
      targetAccount: Expenses:Education:Tuition

    - txType: 跨行汇款
      peerAccountNum: "6214****9332"
      targetAccount: Assets:Zuo:Savings:CMB:9332

    - txType: 网转
      peerAccountNum: "6212****2492"
      targetAccount: Assets:WeiRan:Savings:ICBC:2492

    - txType: 利息
      targetAccount: Income:Zuo:Savings:Interest

    - peer: 财付通-,支付宝-
      ignore: true
    - peer: 支付宝
      txType: 蚂蚁基金赎回到银行
      ignore: true
    - peer: 总行信用卡合伙人
      targetAccount: Income:Bank:ICBC:CreditCard
    - peer: 掌上生活还款
      targetAccount: Liabilities:Bank:CMB:CreditCard
    - txType: 自动还款
      peer: 广东XX分行银行卡中心
      ignore: true
    - peer: 张三,李四,王五
      txTpe: 汇款,网转,汇入
      targetAccount: Assets:Borrow
