defaultMinusAccount: Assets:Zuo:AliPay:Wallet
defaultPlusAccount: Expenses:FIXME
defaultCurrency: CNY
title: 测试
alipay:
  rules:
    # 泛匹配结果应当放在前面

    - type: 收入 # 其他转账收款
      targetAccount: Income:FIXME
      methodAccount: Assets:Zuo:AliPay:Wallet

    - type: 收入 # 收款码收款
      item: 商品
      targetAccount: Income:Alipay:ShouKuanMa
      methodAccount: Assets:Zuo:AliPay:Wallet

    # - type: 收入 
    #   item: 收钱码收款
    #   status: "交易关闭"  #为什么针对交易关闭才忽略的规则对所有交易都生效了
    #   ignore: true

    - category: 日用百货,信用借还
      targetAccount: Expenses:Misc

    - category: 日用百货
      peer: 沃尔玛,盒马,山姆会员商店
      targetAccount: Expenses:Food:Groceries
      
    - category: 日用百货
      item: ALDI奥乐齐超市(东方路店)
      targetAccount: Expenses:Food:Groceries

    - category: 日用百货
      peer: 饿了么
      targetAccount: Expenses:Food:Groceries
      
    - category: 餐饮美食
      targetAccount: Expenses:Food:DinningOut

    - item: 外卖
      targetAccount: Expenses:Food:Takeout

    - peer: 饿了么
      item: 吃货卡
      targetAccount: Expenses:Subscriptions:Shopping:ELeMe

    - category: 餐饮美食
      item: 收钱码收款
      targetAccount: Expenses:Food:FruitSnacks

    - category: 餐饮美食
      item: 零售,货柜
      targetAccount: Expenses:Food:FruitSnacks

    - category: 餐饮美食,日用百货
      peer: 零售,售货
      targetAccount: Expenses:Food:FruitSnacks

    - category: 餐饮美食
      peer: 沙县, 饭
      item: 收钱码收款
      targetAccount: Expenses:Food:DinningOut

    - category: 餐饮美食
      item: 食用油
      targetAccount: Expenses:Food:Groceries

    - category: 生活服务
      type: 支出
      item: 寄件费
      targetAccount: Expenses:Comm:Express

    - category: 公共服务
      peer: 税务
      targetAccount: Expenses:Finance:Taxes

    - category: 日用百货
      type: 支出
      item: 88VIP
      targetAccount: Expenses:Education:Software

    - category: 数码电器
      targetAccount: Expenses:Home:Appliances

    - category: 交通出行
      targetAccount: Expenses:Transport:Taxi

    - category: 交通出行
      item: 汽车票,地铁,火车票
      targetAccount: Expenses:Transport:Public

    - category: 交通出行
      item: 单车,自行车
      targetAccount: Expenses:Transport:Bicycle


    - category: 爱车养车
      targetAccount: Expenses:Transport:Car

    - peer: 停车
      targetAccount: Expenses:Transport:Car:Parking

    - item: 停车
      targetAccount: Expenses:Transport:Car:Parking

    - category: 爱车养车
      item: 保养
      targetAccount: Expenses:Transport:Car:Maintenance

    - peer: 代驾
      targetAccount: Expenses:Transport:Car:Chauffeur

    - category: 文化休闲
      targetAccount: Expenses:Leisure:Entertainment

    - category: 文化休闲
      item: 书籍
      targetAccount: Expenses:Leisure:Books

    - category: 文化休闲
      item: 玩具
      targetAccount: Expenses:Leisure:Toys

    - category: 运动户外
      targetAccount: Expenses:Leisure:Sports

    - category: 教育培训
      peer: 教育
      targetAccount: Expenses:Education:Training

    - type: 支出
      item: 基础软件服务费,Office365
      targetAccount: Expenses:Education:Software

    - type: 支出
      peer: 微软
      targetAccount: Expenses:Education:Software
  
    - category: 充值缴费
      item: 88VIP
      targetAccount: Expenses:Subscriptions:Shopping:88VIP

    - item: Office365,365office
      targetAccount: Expenses:Subscriptions:Software:Office365

    - peer: 爱奇艺
      targetAccount: Expenses:Subscriptions:Video:IQiYi

    - peer: 云视听极光
      targetAccount: Expenses:Subscriptions:Video:QQVideo

    - peer: 芒果TV
      targetAccount: Expenses:Subscriptions:Video:MGTV

    - item: 试卷宝
      targetAccount: Expenses:Subscriptions:Study:ShiJuanBao


    - category: 充值缴费
      peer: 中国电信
      targetAccount: Expenses:Comm:Internet

    - item: justmysocks
      targetAccount: Expenses:Comm:Internet

    - category: 充值缴费
      peer: 上海移动
      targetAccount: Expenses:Comm:PhonePlan

    - category: 保险
      merchantId: CPC
      targetAccount: Expenses:Insurance:Property

    - category: 医疗健康
      targetAccount: Expenses:Health:Medical

    - category: 保险,其他
      item: 好医保,惠琼保
      targetAccount: Expenses:Insurance:Health:Medical

    - category: 亲友代付
      targetAccount: Expenses:ParentsDaily

    - category: 服饰装扮
      item: 黄金,周大福,项链
      targetAccount: Expenses:Shopping:Accessories


    - category: 家居家装
      targetAccount: Expenses:Home:Furniture

    - category: 住房物业
      targetAccount: Expenses:Home:PropertyFee

    - peer: 上海燃气有限公司
      targetAccount: Expenses:Home:Utilities:Gas

    - peer: 国网上海市电力公司(缴费),供电局
      targetAccount: Expenses:Home:Utilities:Electricity

    - peer: 上海浦东威立雅自来水有限公司,南汇自来水
      targetAccount: Expenses:Home:Utilities:Water

    - peer: 滴露
      targetAccount: Expenses:Groceries

    - peer: 星巴克
      targetAccount: Expenses:Food:Drinks

    - item: 相互宝
      targetAccount: Expenses:Insurance

    - item: 药品
      targetAccount: Expenses:Health:Drugs
  
    - peer: 叮当快药
      targetAccount: Expenses:Health:Drugs

    - item: 打印,手工,加工,拼图,diy,DIY
      targetAccount: Expenses:Leisure:Crafting

    - item: 相框
      targetAccount: Expenses:Home:Furniture

    - method: 余额
      fullMatch: true
      methodAccount: Assets:Alipay

    - method: 余额宝
      methodAccount: Assets:Zuo:AliPay:Saving

    - method: 浦发银行信用卡(1765)
      methodAccount: Liabilities:Zuo:CreditCard:SPDB:1765

    - method: 招商银行储蓄卡(9332)
      methodAccount: Assets:Zuo:Savings:CMB:0225

    - method: 农业银行储蓄卡(7911)
      methodAccount: Assets:Zuo:Savings:ABC:7911

    # 交易类型为其他
    - type: 不计收支 #余额宝收入
      item: 收益发放
      methodAccount: Income:Zuo:AliPay:Interest
      targetAccount: Assets:Zuo:AliPay:Saving
    - type: 其他
      item: 余额宝-单次转入
      targetAccount: Assets:Zuo:AliPay:Saving
      methodAccount: Assets:Zuo:AliPay:Wallet

    - type: 不计收支
      item: 余额宝-自动转入
      targetAccount: Assets:Zuo:AliPay:Saving
      methodAccount: Assets:Zuo:AliPay:Wallet

    - peer: 基金
      type: 其他
      item: 黄金-买入
      methodAccount: Assets:Alipay
      targetAccount: Assets:Alipay:Invest:Gold
    - peer: 基金
      type: 其他
      item: 黄金-卖出
      methodAccount: Assets:Alipay:Invest:Gold
      targetAccount: Assets:Alipay
      pnlAccount: Income:Alipay:Invest:PnL
    - peer: 基金
      type: 其他
      item: 买入
      methodAccount: Assets:Alipay
      targetAccount: Assets:Alipay:Invest:Fund
    - peer: 基金
      type: 其他
      item: 卖出
      methodAccount: Assets:Alipay:Invest:Fund
      targetAccount: Assets:Alipay
      pnlAccount: Income:Alipay:Invest:PnL


    - category: 退款
      method: 支付宝
      type: 不计收支
      methodAccount: Expenses:FIXME
      targetAccount: Assets:Zuo:AliPay:Wallet

    - category: 退款
      method: 余额宝
      type: 不计收支
      methodAccount: Expenses:FIXME
      targetAccount: Assets:Zuo:AliPay:Saving
