defaultMinusAccount: Income:Zuo:WeChat:RedPacket
defaultPlusAccount: Expenses:FIXME
defaultCommissionAccount: Expenses:Commission:FIXME
defaultCurrency: CNY
title: 微信交易记录
wechat:
  rules:
    # 基础交易类型规则
    - type: 收入 # 微信红包
      method: /
      item: /
      targetAccount: Income:Zuo:WeChat:RedPacket
    - type: / # 转入零钱
      txType: 转入零钱
      peer: /
      item: /
      targetAccount: Assets:Zuo:WeChat:Wallet
    - type: / # 零钱提现
      txType: 零钱提现
      targetAccount: Assets:Zuo:WeChat:Wallet
      commissionAccount: Expenses:Wechat:Commission
    - type: / # 零钱充值
      txType: 零钱充值
      targetAccount: Assets:Zuo:WeChat:Wallet
    - type: / # 零钱通转出-到工商银行(9876)
      txType: 零钱通转出-到工商银行(9876)
      targetAccount: Assets:Zuo:Bank:ICBC:Savings
    - type: 支出
      txType: 赞赏码
      targetAccount: Expenses:Wechat:Sponsor
    - type: 支出
      txType: 微信红包
      targetAccount: Expenses:Wechat:RedPacket
    - type: 收入
      txType: 微信红包-退款
      targetAccount: Expenses:Wechat:RedPacket

    # 交通出行
    - peer: 中铁网络,上海铁路局,上铁,北京轨道交通互联网票务,杭州杭港地铁有限公司
      targetAccount: Expenses:Transport:Public

    - peer: 停车,平安喜乐,上海国正中心停车场,上海希望医科停车场,INNO创智,上海城投悦城置业有限公司,长泰广场,深圳市顺易通信息科技有限公司,万物云（万科物业母公司）,互联互通停车场,上海益镇物业管理有限公司,上海联讯物业管理有限公司,尚博物业
      type: 支出
      targetAccount: Expenses:Transport:Car:Parking

    - item: 停车,17856
      type: 支出
      targetAccount: Expenses:Transport:Car:Parking

    - peer: 特来电
      type: 支出
      targetAccount: Expenses:Transport:Car:Charging

    - peer: 石油,中国石油
      type: 支出
      targetAccount: Expenses:Transport:Gas

    - peer: 滴滴
      type: 支出
      targetAccount: Expenses:Transport:Taxi

    - item: 高速
      type: 支出
      targetAccount: Expenses:Transport:Car:Toll

    - peer: 妙车坊汽车一站式服务,上海华裕集团
      type: 支出
      targetAccount: Expenses:Transport:Car:Maintenance

    - item: 交通罚没
      targetAccount: Expenses:Transport:Car:Fines

    # 日常消费分类
    - peer: 零售柜,咖啡,coffee,羽神,挥拍羽毛球,Manner,咖啡馆,球馆,七位数体育培训园,TIMHORTONS,星巴克,M Stand,cafe,COSTA,煦荣,饮料,霸王茶姬,上海雨奕信息科技有限公司,饮品,静波体育
      targetAccount: Expenses:Food:Drinks

    - item: 矿泉水,纯净水,自贩机
      targetAccount: Expenses:Food:Drinks

    - peer: 沃尔玛,盒马,山姆会员商店,便利,喜士多,魔盒CITYBOX,全家,罗森,邵万生,铜锣烧,牛奶棚,吉士买生鲜生活超市,上海浦东开市客商业有限公司,LAWSON,奥乐齐
      targetAccount: Expenses:Food:Groceries
      
    - peer: 饿了么,超市
      targetAccount: Expenses:Food:Groceries
      
    - peer: 沙县,饭,餐厅,老乡鸡,炊烟,陈香贵,肯德基,麦当劳,迷迭巷,西贝,望师傅,柳州螺蛳粉,太二,小辣椒,华铁旅客,金桔香港茶餐,赣姐江西小炒大王,重庆小面川菜馆,张子肉串,北京羊城美食,二小姐镇江锅盖面,7柒不腻,香喜嘻兰州牛肉面,杭州盛和商业旅游服务有限公司,北京首都机场餐饮发展有限公司,菜馆
      targetAccount: Expenses:Food:DinningOut

    - peer: 塘桥美好生活馆,大牌档,牛肉面,麻辣烫,馄饨,东北小馆,斑鱼府,小吃店,海棠糕,蒸糕,香港茶餐,台味本舖,羊肉馆,云南菜,拉面,煲仔皇,餐饮管理,美食,快餐,潮府粥道
      targetAccount: Expenses:Food:DinningOut

    - item: 点餐,餐饮,美食,餐厅,拌粉
      targetAccount: Expenses:Food:DinningOut

    - peer: 邵建锋,鲜果,FASCINO
      targetAccount: Expenses:Food:FruitSnacks

    - item: 锅盔
      targetAccount: Expenses:Food:FruitSnacks
    # 快递服务
    - peer: EMS,顺丰,丰巢
      targetAccount: Expenses:Comm:Express

    - item: 寄件费
      targetAccount: Expenses:Comm:Express

    # 个人护理
    - peer: 宜剪
      targetAccount: Expenses:Health:Beauty


    - peer: 上海尧力体育设施有限公司
      targetAccount: Expenses:Education:Training

    # 订阅服务
    - item: 88VIP
      targetAccount: Expenses:Subscriptions:Shopping:88VIP
      
    - peer: 微软
      targetAccount: Expenses:Education:Software

    - item: Steam
      targetAccount: Expenses:Subscriptions:Game:Steam

    - item: Office365,365office
      targetAccount: Expenses:Subscriptions:Software:Office365

    - peer: 爱奇艺,银河奇异果
      targetAccount: Expenses:Subscriptions:Video:IQiYi

    - peer: 云视听极光
      targetAccount: Expenses:Subscriptions:Video:QQVideo

    - peer: 芒果TV
      targetAccount: Expenses:Subscriptions:Video:MGTV

    - item: 试卷宝
      targetAccount: Expenses:Subscriptions:Study:ShiJuanBao

    # 生活缴费
    - peer: 中国电信
      targetAccount: Expenses:Comm:Internet

    - item: justmysocks
      targetAccount: Expenses:Comm:Internet

    - peer: 上海移动,中国移动
      targetAccount: Expenses:Comm:PhonePlan

    - peer: 上海燃气有限公司
      targetAccount: Expenses:Home:Utilities:Gas

    - peer: 国网上海市电力公司(缴费),供电局
      targetAccount: Expenses:Home:Utilities:Electricity

    - peer: 上海浦东威立雅自来水有限公司,南汇自来水
      targetAccount: Expenses:Home:Utilities:Water

    # 居家服务
    - peer: 万物云空间,郭莉莉
      targetAccount: Expenses:Home:PropertyFee

    - peer: 万师傅,宜家,杭州宜家家居有限公司上海分公司
      targetAccount: Expenses:Home:Furniture

    - item: 相框
      targetAccount: Expenses:Home:Furniture

    - item: 不动产登记
      targetAccount: Expenses:Finance:ServiceFee
    # 文具用品
    - peer: 文具,晨光,得力,国誉
      targetAccount: Expenses:Home:Stationery

    - item: 文具,笔记本,笔,橡皮,尺子,订书机,文件夹,便签
      targetAccount: Expenses:Home:Stationery

    # 婴幼儿用品
    - peer: 母婴,宝宝,婴儿,尿不湿,纸尿裤,尿片,尿布,拉拉裤
      targetAccount: Expenses:Home:BabySupplies

    - item: 尿不湿,纸尿裤,尿片,尿布,拉拉裤
      targetAccount: Expenses:Home:BabySupplies

    # 健康保险
    - item: 相互宝
      targetAccount: Expenses:Insurance

    - item: 学平险
      targetAccount: Expenses:Insurance:Life

    - item: 交强险
      type: 支出
      targetAccount: Expenses:Transport:Car:Insurance

    - item: 药品
      targetAccount: Expenses:Health:Drugs
  
    - peer: 叮当快药
      targetAccount: Expenses:Health:Drugs

    - peer: 素问中医,仁济医院,社区卫生
      targetAccount: Expenses:Health:Medical

    # 兴趣爱好
    - item: 打印,手工,加工,拼图,diy,DIY
      targetAccount: Expenses:Leisure:Crafting

    - peer: 美团
      item: 骑
      targetAccount: Expenses:Transport:Bicycle

    - peer: Lucy,Irvin,张立,羊马菜,铃宝宝,百家乐,同学汇
      type: 支出
      txType: 群收款
      targetAccount: Expenses:Leisure:Sports

    - peer: 百家乐
      type: 支出
      txType: 微信红包
      targetAccount: Expenses:Leisure:Sports

    - peer: 趣运动,西可球类中心,西可体育,迪卡侬,中羽联
      type: 支出
      targetAccount: Expenses:Leisure:Sports


    - peer: 优衣库
      type: 支出
      targetAccount: Expenses:Shopping:Clothing

    - peer: 玩刻
      type: 支出
      targetAccount: Expenses:Leisure:Games

    # 购物消费
    - peer: 优衣库,UNIQLO,H&M,ZARA,GAP,UR,太平鸟,森马,美特斯邦威
      type: 支出
      targetAccount: Expenses:Shopping:Clothing

    - peer: 耐克,NIKE,阿迪达斯,ADIDAS,新百伦,NEW BALANCE,匡威,CONVERSE
      type: 支出
      targetAccount: Expenses:Shopping:Shoes

    - peer: 周大福,周生生,六福珠宝,老凤祥
      type: 支出
      targetAccount: Expenses:Shopping:Jewelry

    - peer: 公益基金
      targetAccount: Expenses:Human:Donation

    - peer: 高路顺
      targetAccount: Expenses:Finance:ServiceFee

    # 固定支出
    - peer: 房东
      type: 支出
      targetAccount: Expenses:Housing:Rent

    # 收入相关
    - peer: 用户
      type: 收入
      targetAccount: Income:Service
      tag: income,service

    # 投资理财
    - peer: 理财通
      type: /
      targetAccount: Assets:Trade:Tencent:LiCaiTong

    # 信用卡还款
    - peer: 建设银行
      txType: 信用卡还款
      targetAccount: Liabilities:Bank:CN:CCB

    # 支付方式账户
    - method: / # 一般为收入，存入零钱
      methodAccount: Assets:Zuo:WeChat:Wallet
    - method: 零钱
      fullMatch: true
      methodAccount: Assets:Zuo:WeChat:Wallet
    - method: 零钱通
      fullMatch: true
      methodAccount: Assets:Zuo:WeChat:Wallet
    - method: 浦发银行信用卡(1765)
      methodAccount: Liabilities:Zuo:CreditCard:SPDB:1765
    - method: 招商银行信用卡(7102)
      methodAccount: Liabilities:Zuo:CreditCard:CMB:7102
    - method: 招商银行储蓄卡(0225)
      methodAccount: Assets:Zuo:Savings:CMB:0225

    # 家庭支出
    - item: 亲属卡
      targetAccount: Expenses:ParentsDaily

    - txType: 亲属卡交易-退款
      targetAccount: Expenses:ParentsDaily

    - item: 充电宝
      targetAccount: Expenses:Services:Charging

    # 新增规则

    - peer: 盟迪奥
      type: 支出
      targetAccount: Expenses:Leisure:Entertainment
