defaultMinusAccount: Assets:Zuo:WeChat:Wallet
defaultPlusAccount: Expenses:FIXME
defaultCommissionAccount: Expenses:Commission:FIXME
defaultCurrency: CNY
title: 测试
wechat:
  rules:
    # type (additional condition)
    - type: 收入 # 微信红包
      method: /
      item: /
      targetAccount: Income:Wechat:RedPacket
    - type: / # 转入零钱通
      txType: 转入零钱
      peer: /
      item: /
      targetAccount: Assets:Zuo:WeChat:Wallet
    - type: / # 零钱提现
      txType: 零钱提现
      targetAccount: Assets:Zuo:WeChat:Wallet
      commissionAccount: Expenses:Wechat:Commission
    - type: / # 零钱充值
      txType: 零钱充值
      targetAccount: Assets:Zuo:WeChat:Wallet
    - type: / # 零钱通转出-到工商银行(9876)
      txType: 零钱通转出-到工商银行(9876)
      targetAccount: Assets:Bank:CN:ICBC:Savings
    - type: 支出
      txType: 赞赏码
      targetAccount: Expenses:Wechat:Sponsor

    # 从支付宝导入的规则
    - peer: 沃尔玛,盒马,山姆会员商店
      targetAccount: Expenses:Food:Groceries
      
    - peer: 饿了么
      targetAccount: Expenses:Food:Groceries
      
    - peer: 沙县, 饭
      targetAccount: Expenses:Food:DinningOut

    - item: 寄件费
      targetAccount: Expenses:Comm:Express

    - peer: 税务
      targetAccount: Expenses:Finance:Taxes

    - item: 88VIP
      targetAccount: Expenses:Education:Software

    - peer: 微软
      targetAccount: Expenses:Education:Software
  
    - item: Office365,365office
      targetAccount: Expenses:Subscriptions:Software:Office365

    - peer: 爱奇艺
      targetAccount: Expenses:Subscriptions:Video:IQiYi

    - peer: 芒果TV
      targetAccount: Expenses:Subscriptions:Video:MGTV

    - item: 试卷宝
      targetAccount: Expenses:Subscriptions:Study:ShiJuanBao

    - peer: 中国电信
      targetAccount: Expenses:Comm:Internet

    - item: justmysocks
      targetAccount: Expenses:Comm:Internet

    - peer: 上海移动
      targetAccount: Expenses:Comm:PhonePlan

    - peer: 上海燃气有限公司
      targetAccount: Expenses:Home:Utilities:Gas

    - peer: 国网上海市电力公司(缴费),供电局
      targetAccount: Expenses:Home:Utilities:Electricity

    - peer: 上海浦东威立雅自来水有限公司,南汇自来水
      targetAccount: Expenses:Home:Utilities:Water


    - peer: 星巴克,M Stand
      targetAccount: Expenses:Food:Drinks

    - item: 相互宝
      targetAccount: Expenses:Insurance

    - item: 药品
      targetAccount: Expenses:Health:Drugs
  
    - peer: 叮当快药
      targetAccount: Expenses:Health:Drugs

    - item: 打印,手工,加工,拼图,diy,DIY
      targetAccount: Expenses:Leisure:Crafting

    - item: 相框
      targetAccount: Expenses:Home:Furniture

    # 原有的微信特定规则
    - peer: 塘桥美好生活馆
      type: 支出
      targetAccount: Expenses:Food:DinningOut

    - peer: 云膳过桥米线,餐厅
      sep: ","
      time: 11:00-15:00
      targetAccount: Expenses:Food:Meal:Lunch
    - peer: 云膳过桥米线,餐厅
      sep: ","
      time: 16:30-21:30
      targetAccount: Expenses:Food:Meal:Dinner
    - peer: 餐厅
      time: 23:55-00:10 # test T+1
      targetAccount: Expenses:Food:Meal:MidNight
    - peer: 餐厅
      time: 23:50-00:05 # test T-1
      targetAccount: Expenses:Food:Meal:MidNight

    - peer: 美团平台商户
      type: 支出
      minPrice: 0
      maxPrice: 9.99
      targetAccount: Expenses:Food:Drink
    - peer: 美团平台商户
      type: 支出
      minPrice: 10
      targetAccount: Expenses:Food:Meal

    - peer: 房东
      type: 支出
      targetAccount: Expenses:Housing:Rent

    - item: 停车
      type: 支出
      targetAccount: Expenses:Transport:Car:Parking

    - peer: 用户
      type: 收入
      targetAccount: Income:Service
      tag: income,service

    - peer: 理财通
      type: /
      targetAccount: Assets:Trade:Tencent:LiCaiTong

    - peer: 建设银行
      txType: 信用卡还款
      targetAccount: Liabilities:Bank:CN:CCB

    - method: / # 一般为收入，存入零钱
      methodAccount: Assets:Zuo:WeChat:Wallet
    - method: 零钱
      fullMatch: true
      methodAccount: Assets:Zuo:WeChat:Wallet
    - method: 零钱通
      fullMatch: true
      methodAccount: Assets:Zuo:WeChat:Wallet
    - method: 浦发银行信用卡(1765)
      methodAccount: Liabilities:Zuo:CreditCard:SPDB:1765
    - method: 招商银行信用卡(7102)
      methodAccount: Liabilities:Zuo:CreditCard:CMB:7102
    - method: 招商银行储蓄卡(0225)
      methodAccount: Assets:Zuo:Savings:CMB:0225

    - peer: 测试时间戳
      timestamp_range: 1658112487-1658112490 # order_time= 2022-07-18 10:48:09 ts=1658112489
      targetAccount: Expenses:Travel

    - item: 亲属卡
      targetAccount: Expenses:ParentsDaily