defaultMinusAccount: Assets:Zuo:WeChat:Wallet
defaultPlusAccount: Expenses:FIXME
defaultCommissionAccount: Expenses:Commission:FIXME
defaultCurrency: CNY
title: 测试
wechat:
  rules:
    # type (additional condition)
    - type: 收入 # 微信红包
      method: /
      item: /
      targetAccount: Income:Wechat:RedPacket
    - type: / # 转入零钱通
      txType: 转入零钱
      peer: /
      item: /
      targetAccount: Assets:Zuo:WeChat:Wallet
    - type: / # 零钱提现
      txType: 零钱提现
      targetAccount: Assets:Zuo:WeChat:Wallet
      commissionAccount: Expenses:Wechat:Commission
    - type: / # 零钱充值
      txType: 零钱充值
      targetAccount: Assets:Zuo:WeChat:Wallet
    - type: / # 零钱通转出-到工商银行(9876)
      txType: 零钱通转出-到工商银行(9876)
      targetAccount: Assets:Bank:CN:ICBC:Savings
    - type: 支出
      txType: 赞赏码
      targetAccount: Expenses:Wechat:Sponsor

    - peer: 塘桥美好生活馆
      type: 支出
      targetAccount: Expenses:Food:DinningOut

    - peer: 云膳过桥米线,餐厅
      sep: ","
      time: 11:00-15:00
      targetAccount: Expenses:Food:Meal:Lunch
    - peer: 云膳过桥米线,餐厅
      sep: ","
      time: 16:30-21:30
      targetAccount: Expenses:Food:Meal:Dinner
    - peer: 餐厅
      time: 23:55-00:10 # test T+1
      targetAccount: Expenses:Food:Meal:MidNight
    - peer: 餐厅
      time: 23:50-00:05 # test T-1
      targetAccount: Expenses:Food:Meal:MidNight

    - peer: 美团平台商户
      type: 支出
      minPrice: 0
      maxPrice: 9.99
      targetAccount: Expenses:Food:Drink
    - peer: 美团平台商户
      type: 支出
      minPrice: 10
      targetAccount: Expenses:Food:Meal

    - peer: 房东
      type: 支出
      targetAccount: Expenses:Housing:Rent

    - item: 停车
      type: 支出
      targetAccount: Expenses:Transport:Car:Parking

    - peer: 用户
      type: 收入
      targetAccount: Income:Service
      tag: income,service

    - peer: 理财通
      type: /
      targetAccount: Assets:Trade:Tencent:LiCaiTong

    - peer: 建设银行
      txType: 信用卡还款
      targetAccount: Liabilities:Bank:CN:CCB

    - method: / # 一般为收入，存入零钱
      methodAccount: Assets:Zuo:WeChat:Wallet
    - method: 零钱
      fullMatch: true
      methodAccount: Assets:Zuo:WeChat:Wallet
    - method: 零钱通
      fullMatch: true
      methodAccount: Assets:Zuo:WeChat:Wallet
    - method: 浦发银行信用卡(1765)
      methodAccount: Liabilities:Zuo:CreditCard:SPDB:1765
    - method: 中国银行
      methodAccount: Assets:Bank:CN:BOC:Savings

    - peer: 测试时间戳
      timestamp_range: 1658112487-1658112490 # order_time= 2022-07-18 10:48:09 ts=1658112489
      targetAccount: Expenses:Travel
